"""
Alembic Environment Configuration

This module configures the Alembic migration environment for SQLAlchemy 2.0.
It handles both online (connected to database) and offline (SQL generation only) modes.
"""

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import engine_from_config, pool
from alembic import context
from dotenv import load_dotenv

# Add the backend directory to Python path
sys.path.append(str(Path(__file__).parents[2]))

# Load environment variables
load_dotenv()

# Import all models to ensure they're registered with metadata
from models import (  # noqa: E402
    Base,
    Company,
    FinancialStatement,
    StockPrice,
    FinancialIndicator,
    User,
    Watchlist,
    WatchlistItem,
)

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set the database URL from environment variable
database_url = os.getenv("DATABASE_URL")
if not database_url:
    print("Error: DATABASE_URL environment variable is required")
    print("Set it in your .env file or export it:")
    print("  export DATABASE_URL=postgresql://user:password@host:port/dbname")
    if os.getenv("ENVIRONMENT") == "development":
        print("For development: Check .env.example for configuration template")
    sys.exit(1)

config.set_main_option("sqlalchemy.url", database_url)

# add your model's MetaData object here
# for 'autogenerate' support
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def include_object(object, name, type_, reflected, compare_to):
    """
    Filter for autogenerate to control which objects are included.
    
    This function allows customization of which database objects
    should be included in autogenerated migrations.
    """
    # Include all tables by default
    if type_ == "table":
        return True
    # Include indexes and constraints
    if type_ in ["index", "unique_constraint", "foreign_key_constraint"]:
        return True
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = config.get_main_option("sqlalchemy.url")
    
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        future=True,  # SQLAlchemy 2.0 mode
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            compare_server_default=True,
            # Additional options for better autogenerate
            render_as_batch=False,  # PostgreSQL doesn't need batch mode
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()