"""add watchlists and watchlist_items tables

Revision ID: 463ee6f38c6b
Revises: 24026bf23532
Create Date: 2025-11-09 12:57:03.108264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "463ee6f38c6b"
down_revision: Union[str, None] = "24026bf23532"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_watchlists_id"), "watchlists", ["id"], unique=False)
    op.create_index(
        op.f("ix_watchlists_user_id"), "watchlists", ["user_id"], unique=False
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watchlist_items_company_id"),
        "watchlist_items",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watchlist_items_id"), "watchlist_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_items_watchlist_id"),
        "watchlist_items",
        ["watchlist_id"],
        unique=False,
    )
    op.drop_index("idx_companies_industry_code", table_name="companies")
    op.drop_index("idx_companies_market_division", table_name="companies")
    op.drop_index(
        "idx_financial_indicator_company_date", table_name="financial_indicators"
    )
    op.drop_index("idx_financial_indicator_pbr", table_name="financial_indicators")
    op.drop_index("idx_financial_indicator_per", table_name="financial_indicators")
    op.drop_index("idx_financial_indicator_roe", table_name="financial_indicators")
    op.drop_index("idx_stock_prices_company_date", table_name="stock_prices")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_stock_prices_company_date",
        "stock_prices",
        ["company_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "idx_financial_indicator_roe", "financial_indicators", ["roe"], unique=False
    )
    op.create_index(
        "idx_financial_indicator_per", "financial_indicators", ["per"], unique=False
    )
    op.create_index(
        "idx_financial_indicator_pbr", "financial_indicators", ["pbr"], unique=False
    )
    op.create_index(
        "idx_financial_indicator_company_date",
        "financial_indicators",
        ["company_id", sa.text("date DESC")],
        unique=False,
    )
    op.create_index(
        "idx_companies_market_division", "companies", ["market_division"], unique=False
    )
    op.create_index(
        "idx_companies_industry_code", "companies", ["industry_code"], unique=False
    )
    op.drop_index(op.f("ix_watchlist_items_watchlist_id"), table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_id"), table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_company_id"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_watchlists_user_id"), table_name="watchlists")
    op.drop_index(op.f("ix_watchlists_id"), table_name="watchlists")
    op.drop_table("watchlists")
    # ### end Alembic commands ###
