"""Add data_source field to stock_prices table

Revision ID: 0607ff91625c
Revises: a46e68ea6b0c
Create Date: 2025-11-02 10:39:12.896529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0607ff91625c"
down_revision: Union[str, None] = "a46e68ea6b0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_prices", sa.Column("data_source", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_prices", "data_source")
    # ### end Alembic commands ###
